# Generated by Django 4.2.3 on 2023-07-11 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='additional_info',
        ),
    ]
