# Generated by Django 4.2.3 on 2023-07-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0002_remove_product_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_info',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
