# Generated by Django 4.2.3 on 2023-07-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0005_alter_product_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='appcore/static/uploads/', verbose_name='Product Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image_path',
            field=models.CharField(max_length=200, verbose_name='Image Path'),
        ),
    ]
