# Generated by Django 4.2.3 on 2023-07-17 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0006_product_image_alter_product_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
