# Generated by Django 4.2.3 on 2023-07-17 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0008_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='product_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_path',
        ),
    ]
