# Generated by Django 4.2.3 on 2024-06-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0009_rename_image_product_product_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='cardnumber',
            new_name='card_number',
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='mm',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='number',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='yy',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='images/', verbose_name='Primary Image'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.CharField(default='5', max_length=1),
        ),
    ]
